### ISSUE TITLE
Undefined reference in `petsc_driver` when running `radial_shelf_beach_nonlinear`

### ISSUE THREAD

**Issue by rashidtalha** [rjleveque/ImplicitAMR-paper#1]
I'm running the code in the `radial_shelf_beach_nonlinear` directory.

Calling `make .output` in `1d_radial` works fine and the corresponding plots are generated without any issues. But when I run `make .output` in `radial_shelf_beach_nonlinear` I get errors regarding undefined references in petsc_driver (or amr2.f90).

![Screenshot 2024-03-25 152930](https://github.com/rjleveque/ImplicitAMR-paper/assets/128423607/1c5dedc1-f385-4b84-94e9-4d6fcf0d53b2)

![Screenshot 2024-03-25 152954](https://github.com/rjleveque/ImplicitAMR-paper/assets/128423607/049cb1a0-2e18-4f81-bccc-2c856eca2258)

This worked fine in an earlier version (I'm sorry I don't have it tagged). I have set these environment variables:

```
export CLAW=$PROJECT_DIR/clawpack
export FC=gfortran

export PETSC_DIR=$PROJECT_DIR/petsc-3.20.5
export PETSC_ARCH=arch-linux-c-debug
export PETSC_OPTIONS="-options_file $PROJECT_DIR/implicit-amr-paper/petscMPIoptions"
export OMP_NUM_THREADS=6

export LD_LIBRARY_PATH=$PETSC_DIR/$PETSC_ARCH:$PETSC_DIR/$PETSC_ARCH/lib:$PETSC_DIR/include
```

**Comment by rashidtalha** [comment]
Update: after some experimenting I found that this was caused by some conflicting packages on my system. In particular `pkg-config` was causing trouble. Re-installing it resolved the issue.

**Comment by rjleveque** [comment]
@rashidtalha: Thanks for testing this code and please let us know if you run into other issues.  @mjberger and I are continuing to try to make this easier to use, lots of moving parts!

**Comment by rashidtalha** [comment]
Thank you - I will probably end up emailing you regarding a couple of points where I think I need a bit more clarity. But I'll try these out myself first to see how far I can get.
